### ISSUE TITLE
RFC: Public/Private Keypair Authentication for DAO services

### ISSUE THREAD

**Issue by Flaque** [strangemoodfoundation/strangemood#21]
# Rationale

DAO API services like Metadata and Storage need a way to validate that the `authority` of the `Listing` (ie: the game developer) is the only one allowed to edit the metadata.

# Strategy

1. The Service generates a one-time secret key and encrypts it with the public key of the `authority` it's attempting to validate. 
2. The service then sends that encrypted secret key to the caller of the API. 
3. The caller of the API then uses the private key to decrypt the secret, and then uses it in the `authentication` header of the API request.

## Example: Updating Metadata

**First, the caller of the API requests to "login" as a public key.** 

```
POST /login/<pubkey>
{}
```

**The service responds by creating a secret key, encrypting it with the public key.** Here's an example in pseudocode.

```js
function login(req, res) {
  const pubkey = req.params.pubkey;
  const token = csprng.new(); 
  
  // Store the token on the server, in something like redis.
  redis.set(pubkey, token);  

  const challenge = rsa.encrypt(token, pubkey);
  res.send(challenge);
}
```

**Then, the caller of the API uses their private key (or more likely offloads it to a wallet) to decrypt the challenge.** Here's an example in pseudocode.

```js
const challenge = await api.login(pubkey);
const token = wallet.decrypt(challenge);
```

**Finally, the caller of the API includes the unencrypted token in an `authorization` header as a Bearer token auth, like an API key or session token.**

```js
fetch(`https://metadata.strangemood.org/${pubkey}`, {
   method: "post",
   headers: {
      "Authorization": `Bearer ${token}`
   },
   body: JSON.stringify(myMetadata)
});
```

The service then checks to see if the session token is the same one that matches the public key, and we're good.

**Comment by Flaque** [comment]
Hmm, Kevin says we should consider just having the caller sign something initially rather than the two step process

**Comment by mneira10** [comment]
Ok so after some thought and discussion on discord I think we should implement something similar to [this tutorial for managing logins with metamask](https://www.carlrippon.com/repeat-element-n-times-in-jsx/). The flow to authenticate should look something like this: 

When a user wants to perform an action/send some data they would:

1. Get a `nonce` from the server (a random string) 
2. Sign the `nonce` AND the data with private key (signature = encrypt(`nonce` + data)) 
3. Send encrypted data to server 

The server would then receive the data, decrypt it, verify that the nonce is correct and the perform whatever action is required with the data. 


## Step 1
I think the endpoint could look like:

`/get_nonce?pub_key=<the_public_key>` 

The server would then generate a `nonce`, and store it in its db in a nonces table that would look like:
|nonce|pub_key|
|-|-|
|<generated_nonce>|<the_public_key>|

The nonce  would then be put in a json, encrypted with the public key and sent to the client. The json could be:

```
{
  "nonce":<generated_nonce>
}
```


## Step 2

With the nonce, the client can then perform requests by sending the following payload:

```
{
  "pub_key": ...,
  "encrypted_data": <the_encrypted_data>
}

And the encrypted data would be:

```
{
  "nonce": <the_nonce>,
  "data":  {...}
}
``` 
encrypted with the private key of the client. 

-----

With this approach, we avoid having replay attacks since a new nonce is required on every request
