### ISSUE TITLE
RFC: Storage Service

### ISSUE THREAD

**Issue by Flaque** [strangemoodfoundation/strangemood#25]
# Overview

A service that allows the `authority` of a `Listing` account to upload arbitrary game files, including photos, binaries, or other game data. 

Should use the public/private keypair signing auth strategy as documented in #21 .

## Prior Work

You may want to look at the upload repo that used backblaze that @helenamerk was working on.

**Comment by helenamerk** [comment]
for reference: https://github.com/strangemoodfoundation/upload

**Comment by theFong** [comment]
Is there an api spec for this?

**Comment by theFong** [comment]
I am assuming this service handles retrieval of data as well? Has this been spec'd?
